# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='text',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='title',
        ),
    ]
