# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171008_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
