# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='author',
        ),
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
