# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
